### ISSUE TITLE
More Info on Deployment Steps

### ISSUE THREAD

**Issue by markwk** [MaximeHeckel/health-dashboard#1]
Cool project and nice DIY solution to exporting and taking Apple Health data to the web. I've got [HealthPulse](https://github.com/MaximeHeckel/healthpulse) installed on a device and wondering about how to setup the backend like you have here. 

Can you provide a few more details on how to deploy this? For example, what credentials to change and how to deploy the mongoDB part? 

Thanks!

**Comment by markwk** [comment]
Ok. Mucking about and got a locally working version. I honestly don't really know how all this works. So hacked away to get something. For now, I split this into a separate projects for the backend and web react app. See: https://github.com/markwk/apple-health-sync-backend and https://github.com/markwk/apple-health-web-dashboard. I create some initial docs as well. Just so if anyone else is curious and can save some time. I doubt this is how it was intended to work. 

Next steps will be figuring out how best to deploy this onto something like heroku or whatever.

**Comment by markwk** [comment]
Thanks @MaximeHeckel for the updated docs. Closing...

**Comment by MaximeHeckel** [comment]
Glad to hear that!
