### ISSUE TITLE
Docker File Fails 

### ISSUE THREAD

**Issue by markwk** [MaximeHeckel/health-dashboard#2]
Still some irregularities in the docker make and I'm getting various errors running $ docker-compose up. 

### 1. Go Server Doesn't Start Due to Linking Issues

`Step 4/23 : RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -a -installsuffix cgo -v -o server
 ---> Running in a0b17390009e
utils/utils.go:9:2: cannot find package "gopkg.in/mgo.v2" in any of:
	/go/src/github.com/MaximeHeckel/healthDashboard/go/src/server/vendor/gopkg.in/mgo.v2 (vendor tree)
	/usr/local/go/src/gopkg.in/mgo.v2 (from $GOROOT)
	/go/src/gopkg.in/mgo.v2 (from $GOPATH)
apihandlers/apihandlers.go:14:2: cannot find package "gopkg.in/mgo.v2/bson" in any of:
	/go/src/github.com/MaximeHeckel/healthDashboard/go/src/server/vendor/gopkg.in/mgo.v2/bson (vendor tree)
	/usr/local/go/src/gopkg.in/mgo.v2/bson (from $GOROOT)
	/go/src/gopkg.in/mgo.v2/bson (from $GOPATH)
ERROR: Service 'healthdashboard' failed to build: The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -ldflags '-s' -a -installsuffix cgo -v -o server' returned a non-zero code: 1`

### 2. Go Server Name Doesn't Match Github Repo

For example, Dockerfile, go/src/server/main.go and various other files call for github.com/MaximeHeckel/healthDashboard.  I believe this should be updated to match github.com/MaximeHeckel/health-dashboard since govendor pulls there. 

### 3. Directly Running Go Server Fails

Similarly when I run go run main.go inside of /server in the go directory it fails. Compare this with: https://github.com/markwk/apple-health-sync-backend/blob/master/main.go which does work after running govendor for that repo.

**Comment by MaximeHeckel** [comment]
Thanks for reporting this, will look at it ASAP
I agree the Go "experience" is a bit odd, I'll try to improve this as much as possible

**Comment by MaximeHeckel** [comment]
1. Is due to a gitsubmodule issue I'm going to add the proper command in the Dockefile and the README

2. You're right I'm going to fix this, it needs to match

3. In order to run the go server locally you need to put it in a folder that matches the repo url otherwise it won't start.

I'll put up a PR ASAP

**Comment by MaximeHeckel** [comment]
@markwk can you try to run `git submodule update --init --recursive` at the root of the project and then `docker-compose up`?

**Comment by MaximeHeckel** [comment]
Running `git submodule update --init --recursive` before running the project should fix this
Closing this. Will reopen if the issue persists
